config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :wishes do
    resources :likes, only: [:create]
  end

  resources :matches, only: [:show, :index, :create, :destroy] do
    resources :locations, only: [:show, :index]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_dropdown.html.erb
<div class="arrow">
  <% toto = @user_wish&.sport&.name %>
  <div class="text-center select-box">
    <%= simple_form_for Wish.new, url: wishes_path, method: :post, data: { controller: "wish-dropdown" } do |f| %>
      <%= f.input :sport,
                  collection: Sport.all.pluck(:name),
                  prompt: ("Select a sport" unless toto),
                  selected: (toto if toto),
                  label: false,
                  error: 'Please select a sport to begin your journey',
                  required: false,
                  wrapper_html: { class: 'wish-form-group' },
                  input_html: { class: "home-dropdown #{"wish-index-dropdown" if controller_name == "wishes" && action_name == "index"}", data: { action: "input->wish-dropdown#submit", wish_dropdown_target: 'select' } } %>
      <i class="fas fa-angle-down"></i>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer justify-content-between">
  <ul>
    <li>
      <%= link_to root_path, class: "btn #{action_name == "home" ? "active" : ""}" do %>
        <i class="mb-1 mt-1  fas fa-home"></i>
        <p class='text-muted footer-font'>Home</p>
      <% end %>
    </li>
    <li>
      <%= link_to matches_path, class: "btn #{controller_name == "matches" ? "active" : ""}" do %>
        <i class="mb-1 mt-1  fas fa-hands-helping"></i>
        <p class='text-muted footer-font'>Buddies</p>
      <% end %>
    </li>
    <li>
      <%= link_to wishes_path, class: "btn #{controller_name == "wishes" && action_name == "index" ? "active" : ""}" do %>
        <i class="mb-1 mt-1  fas fa-search"></i>
        <p class='text-muted footer-font'>Search</p>
      <% end %>
    </li>
  </li>
  <li>
    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Do you really want to sign out?" } do %>
        <i class="mb-1 mt-1  fas fa-user"></i>
        <p class='text-muted footer-font'>Sign out</p>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "btn" do %>
        <i class="mb-1 mt-1  fas fa-user"></i>
        <p class='text-muted footer-font'>Sign in</p>
      <% end %>
    <% end %>
  </li>
</ul>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="bg-transparent navbar">
    <%= link_to image_tag('icon.png', width: 90), root_path %>
</div>