config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :wishes do
    resources :likes, only: [:create]
  end

  resources :matches, only: [:show, :index, :create, :destroy] do
    resources :locations, only: [:show, :index]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :location
  has_many :wishes
  has_many :users, through: :wishes

  def address
    location.address
  end

  def chatroom
    user, other_user = wishes.map { |wish| wish.user }

    Chatroom.where(
      "(user1_id = :user_id AND user2_id = :other_user_id)
        OR
      (user1_id = :other_user_id AND user2_id = :user_id)",
      user_id: user.id,
      other_user_id: other_user.id
    ).first
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    @match = Match.find(params[:id])
    authorize @match
    locations = Location.where(sport_id: @match.wishes.first.sport_id)
    @location = locations[0];
    @marker = [{
      lat: @location.latitude,
      lng: @location.longitude,
      info_window: render_to_string(partial: "info_window", locals: { location: @location }),
      image_url: helpers.asset_url('blue-marker.jpg')
    }]
    # @match.wishes.each do |wish|
    # locations.each do |location|
    #   if @match.wishes.last.user != current_user
    #     @location = location
    #     @marker =[{
    #       lat: location.latitude,
    #       lng: location.longitude,
    #       info_window: render_to_string(partial: "info_window", locals: { location: location }),
    #       image_url: helpers.asset_url('blue-marker.jpg')
    #     }]
    #   end
    # end
  end

  def index
    @matches = policy_scope(Match)
  end

  def create
  end

  def destroy
    @match = Match.find(params[:id])
    authorize @match
    @match.destroy
    redirect_to matches_path
  end
end

app/views/matches/_info_window.html.erb
<h2><%= location.name %></h2>
<p><%= location.address %></p>

app/views/matches/_recent_match.html.erb
<%#= current_user.current_matched_wish.user.username %>
<%#= current_user.current_matched_wish.user.age %>
<%#= current_user.current_matched_wish.sport.name %>

app/views/matches/_swal_content.html.erb
<div>
  <%= cl_image_tag user.photo.key, class: "avatar" %>
  <p><%= user.username %></p>
  <%= link_to "Chat", chatroom_path(chatroom), class: "chat-button" %>
</div>

app/views/matches/index.html.erb
<%# current_user.current_matched_other_wish do |wish| %>
<%# <div class="card-current-match">
  <% if current_user.current_matched_wish %>
    <%# <%= cl_image_tag current_user.current_matched_wish.user.photo.key, class: 'img-index' %>
    <!--<img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg"> !-->
    <%# <div class="card-current-match-infos">
      <div>
        <%= render "recent_match" %>
      <%# </div>
    </div>
  <% else %>
    <%# <h2><%= No Match found %>
  <%# <% end %>
<%# </div> %>
<ul class="flex-column card-match">
  <% current_user.likes.where(liked: true).joins(wish: :match).each do |like| %>
    <%= link_to match_path(like.wish.match) do %>
      <div class="card-other-matches">
        <%= cl_image_tag like.wish.user.photo.key, class: 'img-index ml-2' %>
        <div class="card-other-matches-infos">
          <li><p><%= like.wish.user.username %>, <%= like.wish.user&.age %> years old</p></li>
          <li class="tag wish-tag" style="color: #8d2929"><%= like.wish.sport.name %></li>
        </div>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/matches/show.html.erb
<div class="matches-show navbar-padding">
  <div class="card-current-match">
    <%# Wish.where.not(user: self).where(match_id: @match.id).user.photo.key %>
    <% @match.wishes.each do |wish| %>
      <% if wish.user != current_user %>
        <%= cl_image_tag wish.user.photo.key, class: 'img-index' %>
        <div class="match-card-details">
          <h2><%= wish.user.username %>, <%= wish.user.age %> years old</h2>
          <div class="wish-tag">
            <%= wish.sport.name %></p>
          </div>
        </div>
      <% end %>
    <% end %>

    <div class="px-3 d-flex align-iems-center match-card-location" data-toggle="modal" data-target="#exampleModal">
      <i class="fas fa-map-marked-alt fa-2x d-flex align-items-center mr-3"></i>
      <% if @location %>
      <div>
        <strong><%= @location.name %></strong>
        <div><%= @location.address %> <i class="fas fa-external-link-alt ml-1"></i></div>
      </div>
      <% end %>
    </div>
    <div class="card-current-match-infos">
      <%# <div>
        <%= render "recent_match" %>
      <%# </div> %>
    </div>
    <%# <div class="container chat-button-show"> %>
    <div class="d-flex align-items-center justify-content-center p-3">
      <%= link_to chatroom_path(@match.chatroom), class: "btn btn-danger btn-flat" do %>
        <i id="chat-link" class="far fa-comments fa-2x"></i>
        <span>Chat</span>
      <% end %>
    <%# </div> %>
<%#       <button type="button" class="btn btn-danger btn-flat" data-toggle="modal" data-target="#exampleModal">
        <i class="fas fa-map-marked-alt fa-2x"></i>
        <span>Location</span>
      </button> %>
    </div>
  </div>

<%# if policy(Match).destroy? %>
  <%#= link_to "Delete", matches_path, class: "delete-button", :confirm => 'Are you sure?', :method => :destroy %>
<%# end %>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your sports location</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="map"
          style="width: 100%; height: 300px;"
          data-markers="<%= @marker.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

</div>